'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import TodaysMatchesWidget from '@/components/About/TodaysMatchesWidget';
import StrategyContentSection from '@/components/Academy/StrategyContentSection';
import StrategyTOC from '@/components/Academy/StrategyTOC';

const sections = [
  { 
    id: 'metric-analysis', 
    title: 'Metric Analysis: The Anatomy of a Corner', 
    content: (
      <>
        Corner betting is the clinical analysis of <strong>territorial dominance</strong>. While goal markets are often dictated by individual moments of brilliance, corners are the byproduct of sustained attacking pressure. In professional markets, the corner count is the most reliable proxy for a team&apos;s &quot;Attacking Urgency&quot; and defensive desperation.
        <br /><br />
        <strong>The Core Dynamics:</strong>
        <br />
        • <strong>Pressure Byproduct:</strong> Corners are generated by blocked crosses, deflected shots, and goalkeeper interventions.
        <br />
        • <strong>Market Isolation:</strong> Corner markets allow you to profit from a team&apos;s dominance even if they fail to find the back of the net.
      </>
    ),
    advantages: [],
    risks: []
  },
  { 
    id: 'generator-analysis', 
    title: 'Width and Cross-Volume: The Corner Generators', 
    content: (
      <>
        Professional corner analysts prioritize <strong>Tactical Architecture</strong> over historical averages. A team&apos;s corner yield is directly correlated to their use of the pitch&apos;s width.
        <br /><br />
        <strong>Indicators of High Corner Yield:</strong>
        <br />
        • <strong>Wing-Back Overlaps:</strong> Teams that utilize offensive wing-backs (e.g., Liverpool or Bayer Leverkusen) create more diagonal entry points into the box, leading to a higher frequency of defensive deflections.
        <br />
        • <strong>Shot-Volume:</strong> Teams with a high &quot;Shots-from-Distance&quot; metric force more goalkeeper parries, which are a primary source of 90th-minute corner spikes.
      </>
    ),
    advantages: [],
    risks: []
  },
  { 
    id: 'game-state-desperation', 
    title: 'Game-State Volatility: The Desperation Spike', 
    content: (
      <>
        The most predictable variable in corner betting is the <strong>Trailing Favorite</strong>. When an elite team is losing by 1 goal after the 70th minute, their &quot;Verticality&quot; increases exponentially.
        <br /><br />
        <strong>The &quot;Desperation Pressure&quot; Effect:</strong>
        <br />
        During this interval, the trailing team will bypass midfield build-up and flood the box with crosses. This state of perpetual pressure often leads to 3 or 4 corners in a 10-minute window, making &quot;In-Play Over&quot; markets high-yield strategies for reactive bettors.
      </>
    ),
    advantages: [],
    risks: []
  },
  { 
    id: 'handicap-refinement', 
    title: 'Handicaps and Ranges: Refining Your Edge', 
    content: (
      <>
        While &quot;Match Totals&quot; are common, <strong>Corner Handicaps</strong> offer superior professional value. If a dominant home team is at -4.5 corners, they must win the corner count by 5 or more.
        <br /><br />
        <strong>Technical Comparison:</strong>
        <br />
        • <strong>Handicaps:</strong> Used when you expect one-sided territorial control.
        <br />
        • <strong>Ranges (e.g., 9-11):</strong> Used in high-parity matches where you expect a &quot;mid-block&quot; battle. Ranges offer higher coefficients but require precise knowledge of the match&apos;s &quot;Tactical Ceiling.&quot;
      </>
    ),
    advantages: [],
    risks: []
  },
  { 
    id: 'conclusion', 
    title: 'The Territorial Advantage', 
    content: (
      <>
        Corner betting is the ultimate market for those who understand the <strong>flow of the game</strong>. It rewards the analyst who looks at the pitch as a battle for territory rather than just a scoreboard. Master the width, anticipate the desperation, and corners will provide a consistent high-alpha alternative to goal-based betting.
      </>
    ),
    advantages: [],
    risks: []
  },
  { 
    id: 'faqs', 
    title: 'Expert Q&A', 
    content: '',
    advantages: [],
    risks: [],
    faqs: [
      {
        question: "Do corners in Extra Time count?",
        answer: "Standard corner markets are settled at the 90-minute mark (including injury time). Any corners won during Extra Time are typically only included in specific &apos;Live Extra Time&apos; markets."
      },
      {
        question: "What is the 'Multi-Corner' market?",
        answer: "This is a specialized market where the number of first-half corners is multiplied by the number of second-half corners. It is a high-volatility market that rewards &apos;Interval&apos; specialists."
      },
      {
        question: "How do early goals affect the corner count?",
        answer: "An early goal for the favorite can &apos;kill&apos; the corner market. If the favorite leads 2-0 early, they often reduce their attacking intensity and focus on possession, significantly lowering the total corner expectation."
      },
      {
        question: "Does pitch size matter for corners?",
        answer: "Width is critical. Narrower pitches reduce the space for wingers to beat defenders and deliver crosses, which can lead to a &apos;congested&apos; game state and fewer corners compared to wide, expansive pitches."
      }
    ]
  }
];

export default function CornerBettingPage() {
  const [activeSection, setActiveSection] = useState(sections[0].id);
  const [scrollProgress, setScrollProgress] = useState(0);

  useEffect(() => {
    const handleScroll = () => {
      const totalScroll = document.documentElement.scrollHeight - window.innerHeight;
      if (totalScroll > 0) {
        setScrollProgress((window.scrollY / totalScroll) * 100);
      }
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      const intersecting = entries.filter(e => e.isIntersecting);
      if (intersecting.length > 0) {
        setActiveSection(intersecting[intersecting.length - 1].target.id);
      }
    }, { rootMargin: '-10% 0px -70% 0px', threshold: [0, 0.1, 0.2] });
    
    sections.forEach(s => {
      const el = document.getElementById(s.id);
      if (el) observer.observe(el);
    });
    return () => observer.disconnect();
  }, []);

  return (
    <div className="min-h-screen bg-[#F8FAFC]">
      <div className="fixed top-0 left-0 w-full h-1.5 z-50 bg-slate-100">
        <div className="h-full bg-brand-emerald transition-all duration-150 ease-out" style={{ width: `${scrollProgress}%` }} />
      </div>

      <div className="max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
        <nav className="flex items-center gap-2 text-xs font-medium text-slate-400 mb-8 overflow-x-auto whitespace-nowrap pb-2">
          <Link href="/" className="hover:text-brand-emerald transition-colors">HOME</Link>
          <span className="text-slate-300">/</span>
          <Link href="/academy" className="hover:text-brand-emerald transition-colors uppercase">ACADEMY</Link>
          <span className="text-slate-300">/</span>
          <Link href="/academy/bet-type" className="hover:text-brand-emerald transition-colors uppercase">BET-TYPES</Link>
          <span className="text-slate-300">/</span>
          <span className="text-brand-emerald uppercase font-bold">CORNER BETTING GUIDE | LEARN...</span>
        </nav>

        <div className="flex flex-col lg:flex-row gap-12">
          <main className="flex-1 min-w-0 order-2 lg:order-1">
            <header className="mb-12">
              <h1 className="text-4xl sm:text-5xl font-black text-slate-900 mb-8 tracking-tight leading-[1.1]">
                Corner Betting <span className="text-brand-emerald">Masterclass</span>
              </h1>
              
              <div className="bg-white rounded-[40px] p-8 sm:p-12 border border-slate-100 shadow-xl shadow-slate-200/50 mb-12">
                <div className="prose prose-slate prose-lg max-w-none">
                  <p className="text-xl text-slate-600 leading-relaxed font-semibold mb-6 italic">
                    &quot;Corners are the ultimate proxy for territorial dominance—a byproduct of pressure that goal-based markets often ignore.&quot;
                  </p>
                  <p className="text-slate-500 leading-relaxed">
                    In this technical guide, we break down the clinical anatomy of a &apos;Corner Kick.&apos; We analyze the tactical generators of width and cross-volume, reveal the predictable &apos;Desperation Spike&apos; in game-state volatility, and provide a professional framework for refining your edge using Handicaps and Range betting.
                  </p>
                </div>
              </div>
            </header>

            <div className="space-y-20">
              {sections.map((section) => (
                <StrategyContentSection 
                  key={section.id}
                  {...section} 
                  isActive={activeSection === section.id} 
                />
              ))}
            </div>
          </main>

          <aside className="w-full lg:w-[380px] space-y-8 order-1 lg:order-2">
            <div className="sticky top-24 space-y-8">
              <StrategyTOC 
                sections={sections} 
                activeSection={activeSection} 
                onSectionChange={(id) => {
                  setActiveSection(id);
                  const el = document.getElementById(id);
                  if (el) window.scrollTo({ top: el.offsetTop - 100, behavior: 'smooth' });
                }} 
              />
              <div className="hidden lg:block">
                <TodaysMatchesWidget />
              </div>
            </div>
          </aside>
        </div>
      </div>
    </div>
  );
}
